### ISSUE TITLE
Reporting cached information

### ISSUE THREAD

**Issue by red-erik** [vletoux/pingcastle#209] opened 2024-01-26 08:30 UTC
Hello,
when we run the tool to have HTML report, we have information related to completely dismissed subdomains (no more existing Domain controllers, no DNS records or related records into ADDS).
Why the tool is still reporting information on them ?

Regards,
Red.

**Comment by An-dir** [comment] 2024-01-26 09:12
Where in the report did you find the "cached information"? Is it just SIDs or full trust information. You may have forgotten to check the Domains and Trusts mmc "domain.msc"

Did you ckeck as well that there are no Trust objects anymore in that area: 
`CN=System,DC=domain,DC=tld`

**Comment by red-erik** [comment] 2024-01-26 10:02
Hello,
I confirm the everything is gone but the tool is still reporting a lot of details related to number of users/grops etc.etc.. We use a scheduled task to run the tool always into the same directory (to easly publish the HTML as Web Vdir). If we run it in another clean directory, the cached information are not present any more.

Regards,
Red.

**Comment by vletoux** [comment] 2024-01-28 16:05
I do not see a bug report here.
Closing ...

**Closed by vletoux** 2024-01-28 16:05 UTC

**Comment by red-erik** [comment] 2024-01-29 07:46
Hello, 
it seems that the tool is reading on subfolders (History). If we delete it, no cached information is reported.
Regards,
Red.

**Comment by vletoux** [comment] 2024-01-29 16:28
For doing consolidation / map ?
This is not a bug but a feature.
